@dev = 

@prod = 

@local = http://localhost:3000

###
GET {{local}}/api/v1/users


###
GET {{local}}/api/v1/users/645e6d4f84015102c7e6ff1c


###
POST {{local}}/api/v1/users
Content-Type: application/json

{
  "firstName": "Phone",
  "lastName": "Waiyam Hein",
  "username": "pwh",
  "password": "nilar",
  "email": "pwh@eureka.com",
  "avatar": "",
  "roleId": "645e0bf83ad3840707a612f2"
}


###
PUT {{local}}/api/v1/users/645e6d4f84015102c7e6ff1c
Content-Type: application/json

{
  "firstName": "Nilar",
  "lastName": "Win Htut",
  "username": "nwh",
  "password": "nilar",
  "email": "nwh@eureka.com",
  "avatar": "",
  "roleId": "645e0bf83ad3840707a612f2"
}




###
DELETE {{local}}/api/v1/users/645928991ae2995fcfe816c0